ydRSoft.Web/Areas/AConfiguracion/Controllers/ConfiguracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ydRSoft.BL;
using ydRSoft.Modelo;

namespace ydRSoft.Web.Areas.AConfiguracion.Controllers
{
    public class ConfiguracionController : Controller
    {
        // GET: AConfiguracion/Configuracion
        public ActionResult Index()
        {
            UsuarioModel model = (UsuarioModel)Session["objUser"];
            if (model == null)
            {
                return RedirectToAction("Login", "Home", new { Area = string.Empty });
            }

            return View(model);
        }

        public  ActionResult VerConfig()
        {  
            return PartialView("_verConfig");
        }
    }
}

ydRSoft.Web/Controllers/HomeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ydRSoft.BL;
using ydRSoft.Modelo;

namespace ydRSoft.Web.Controllers
{
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index()
        {
            //var mUser = await UsuarioBL.GetUsuarioId(2);

            //Session["objUser"] = mUser;

            UsuarioModel model = (UsuarioModel)Session["objUser"];         

            //return RedirectToAction("Index", "Configuracion", new { Area = "AConfiguracion" });
            //return RedirectToAction("About", "Home", new { Area = string.Empty });

            if (model == null)
            {
                return RedirectToAction("Login");
            }

            await InfoSing.Instance.LoadProductos();
            //await SugerenciaBL.LoadSugerencia(model.Id);

            return View(model);
        }

        public ActionResult Login()
        {

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ydRSoft.Web/Views/Home/Login.cshtml
@{
    Layout = null;
    ViewBag.Title = "Login";
}

<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* Altura completa de la pantalla */
            margin: 0;
        }

        .mi-caja {
            width: 40%;
            background-color: white;
            padding: 20px 80px;
            box-sizing: border-box;
            border-radius: 15px;
            margin: 0; /* Quita los márgenes, ya que el flexbox se encarga del centrado */
        }
        

        .mi-input {
            width: 100%;
            border-radius: 10px;
            padding: 10px;
            font-size: 16px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            color: navy;
            outline: none;
        }

        .color_btn1a {
            background-color: #3D9656;
            color: white;
            border: none;
            border-radius: 15px;
            padding: 10px;
            width: 100%;
            cursor: pointer;
            margin: 15px auto;
            display: block;
            box-sizing: border-box;
            font-size:24px;
        }



        .color_btn2b {
            color: #fff;
            background-color: #1F6332;
            border: none;
            border-radius: 15px;
            padding: 10px;
            width: 100%;
            cursor: pointer;
            margin: 15px auto;
            display: block;
            box-sizing: border-box;
            font-size: 24px;
        }

        .color_btn3c {
            color: #fff;
            background-color: #17341E;
            border:none;
            border-radius: 15px;
            padding: 10px;
            width: 100%;
            cursor: pointer;
            margin: 15px auto;
            display: block;
            box-sizing: border-box;
            font-size: 24px;
        }

        .div-centrado{
            text-align:center;
        }

        

    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title> SK |  @ViewBag.Title</title>

    <link rel="shortcut icon" href="~/Content/Imagenes/Logos/gorrito-sk1.png">

    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/font-awesome/css/font-awesome.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/css/animate.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/css/estiloydR.css")" rel="stylesheet">

</head>


<body style="background-color: black; font-size: 24px">
    <div class="mi-caja">
        <div class="div-centrado">
            <img src="~/Content/Imagenes/Logos/sk_logo.png" height="250" />
        </div>
        <br />
        <div id="verLogin">
            <div class="form-group text-left">
                Usuario <br />
                <input id="mUser" class="mi-input" autocomplete="off" placeholder="Di tu usuario" maxlength="25" onkeyup="funEntrar(event)"/>
            </div>
            <div class="form-group text-left">
                Clave<br />
                <input type="password" id="mClave" class="mi-input" autocomplete="off" placeholder="Di tu Clave" onkeyup="funEntrar(event)"/>
            </div>
        </div>
        <p>Di la accion que deseas realizar:</p>
        <button class="color_btn1a" onclick="funIngresar(1)" id="btnIngresar"> Ingresar</button>
        <button class="color_btn2b" onclick="funIngresar(2)" id="btnRegistro"> Registrar</button>
        <button class="color_btn3c" onclick="funIngresar(0)" id="btnInvitado"> Invitado</button>
        <span id="mMensaje1a" class="text-danger"></span>
        <div id="clockDiv" class=" text-center text-black-50"></div>
    </div>

    
    <!-- Mainly scripts -->
    <script src="@Url.Content("~/Content/ydrsoft/JSutil.js")"></script>
    <script src="@Url.Content("~/Content/js/jquery-3.1.1.min.js")"></script>
    <script src="@Url.Content("~/Content/js/popper.min.js")"></script>
    <script src="@Url.Content("~/Content/js/bootstrap.js")"></script>

</body>
</html>

<script id="_Captura_de_voz_">

    function VozTextoYdR(texto) {
        const utterance1a = new SpeechSynthesisUtterance(texto); // Crear una nueva instancia de SpeechSynthesisUtterance
        window.speechSynthesis.speak(utterance1a); // Hablar el texto
    }

    const recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();

    recognition.lang = 'es-ES';
    recognition.interimResults = false;
    recognition.maxAlternatives = 1;

    recognition.start();
    function normalizarTexto(texto) {
        // Reemplaza la "á" por "a" y convierte todo a minúsculas
        return texto.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
    }

    recognition.onresult = (event) => {
        const transcript = event.results[0][0].transcript.toLowerCase();
        //const textoNormalizado = normalizarTexto(transcript); // Normalizar el texto
        console.log('Transcripción:', transcript); // Mostrar la transcripción en la consola


        if (transcript === 'usuario') {            
            setFocus('mUser');
        } else {
            if (transcript === 'clave') {
                setFocus('mClave');
            } else {                
                if (transcript === 'ingresar') {
                    funIngresar(1);
                } else {
                    if (transcript === 'invitado') {
                        funIngresar(0);
                    } else {
                        if (transcript === 'registrar') {
                            funIngresar(2);
                        } else {
                            if (transcript === 'limpiar') {
                                document.getElementById('mUser').value="";
                                document.getElementById('mClave').value = "";
                                setFocus('mMensaje1a')
                            } else {
                                EscribirTexto(transcript);
                            }

                        }
                    }
                }
            }
        }
    };

    recognition.onerror = (event) => {
        console.error('Error de reconocimiento de voz:', event.error);
    };

    recognition.onend = () => {
        recognition.start();
    };
</script>


<script>

    function funEntrar(event) {
        if (event.key === 'Enter') {
            console.log("entro con enter");
            funIngresar(1);
        }
    }

    setFocus('mUser');
    function EscribirTexto(txtLetra) {
        const elementoActivo = document.activeElement;

        // Verifica si el elemento activo es un input de texto
        if (elementoActivo.tagName === "INPUT") {
            // Reemplaza cualquier texto anterior con el nuevo texto
            let resultado = txtLetra.replace(/\s+/g, '');
            elementoActivo.value = resultado;
        } else {
            console.log("No hay ningún input de texto enfocado.");
        }

    }

    async function funIngresar(opc) {
        console.log("ingreso");        
        let nombre = document.getElementById('mUser').value;
        let clave = document.getElementById('mClave').value;

        let tamnom = nombre.length;
        let tamcla = clave.length;

        if (opc != 0) {

            if (tamnom == 0) {
                setTextIn('mMensaje1a', "Por favor, Ingrese un Nombre");
                VozTextoYdR("Por favor, Ingrese un Nombre");
                setFocus('mUser');
                return;
            } 

            if (tamcla == 0) {
                setTextIn('mMensaje1a', "Por favor, Ingrese una Contraseña");
                VozTextoYdR("Por favor, Ingrese una Contraseña");
                setFocus('mClave');
                return;
            }
        }

        initUsuario(opc);

        console.log("salio");
    }

    async function initUsuario(opc) {
        
        let nombre = document.getElementById('mUser').value;
        let clave = document.getElementById('mClave').value; 

        //setDisabled(entrada, true);
        var dataString = new FormData();
        dataString.append("Nombre", nombre);
        dataString.append("Clave", clave);
        dataString.append("Opcion", opc);

        const response = await fetch('/AUsuario/Usuario/InicioUsuario', {
            method: 'POST',
            body: dataString,
        });

        if (response.ok) {
            const data = await response.json();
            if (data.Error) {
                setTextIn('mMensaje1a', data.Mensaje)
                VozTextoYdR(data.Mensaje);
            } else {
                window.location.href = '/Home/Index';
            }

        } else {
            console.log('Error en la respuesta: ' + response.status, response.statusText);
        }

        //setDisabled(entrada, false);
    }


    function setFocus(entrada) {
        let outInput = document.getElementById(entrada);
        if (outInput && typeof outInput.focus === 'function') {
            outInput.focus();
        }
    }

    function setDisabled(entrada, activo) {
        let outInput = document.getElementById(entrada);
        let contenidoHTML = outInput.innerHTML; 
        console.log(contenidoHTML);
        outInput.disabled = activo;

        if (activo) {
            outInput.innerHTML = "CARGANDO &nbsp; &nbsp; <i class='fa fa-spinner'></i>";
        } else {
            outInput.innerHTML = contenidoHTML;
        }
    }

    function setTextIn(entrada, texto) {
        let outInput = document.getElementById(entrada);
        outInput.innerHTML = texto;
    }


    function validarFoco(entrada) {
        const input = document.getElementById(entrada);
        if (document.activeElement === input) {
            alert("El input está enfocado.");
        } else {
            alert("El input NO está enfocado.");
        }
    }

   
</script>

ydRSoft.Web/Views/Home/_verBotones.cshtml
<style>
    .circular-button7c {
        width: 30px;
        height: 30px;
        border: 2px solid rgb(64, 150, 84);
        border-radius: 50%;
        background-color: transparent;
        color: rgb(64, 150, 84);
        font-size: 15px;
        text-align: center;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }
</style>

<div class="floatingBotones">
    <div>
        <button class="circular-button7c" onclick="funConfiguracion()"><i class="fa fa-gears"></i></button>
        <hr />
    </div>
    <div id="tiempoEjec"> 0s </div>
    <button class="circular-button7c" id="btnComandos" onclick="funComandos()">1</button>
    <button class="btn btn-circle btn-success" id="startCapture" onclick="IniciarCaptura()">2</button>
    <button class="circular-button7c" id="btnReceta" onclick="funRecetas()">3</button>
    <button class="circular-button7c" id="btnMenu" onclick="funMenu()">4</button>
    <button class="circular-button7c" id="btnFavoritos" onclick="funFavoritos()">5</button>
    <button class="circular-button7c" id="btncategoria" onclick="funCategoria()">6</button>
    <button class="circular-button7c" id="btnBotones" onclick="funBotones()">7</button>
    <button class="circular-button7c" id="btnConfiguracion" onclick="funAddFavorito()">8</button>
    <button class="circular-button7c" id="btnSalir" onclick="funSalir()">9</button>
    <button class="circular-button7c" id="btnReiniciar" onclick="funReiniciar()" hidden>9</button>
    <button class="circular-button7c" id="btnPantalla" onclick="funPantalla()" hidden>11</button>
</div>

<script>
    function funComandos() {
        funModales('modalComandos');
    }

    function funMenu() {
        if (esVisible('vistaMenu')) {

            setOcultar('vistaMenu', true);
        } else {
            setOcultar('vistaMenu', false);
        }
    }

    function funFavoritos() {
        console.log("ver favoritos XD");
        funVerFavorito();
    }

    function funCategoria() {
        funModales('modalCategoria');
    }

    function funConfiguracion() {
        
        let iduser = document.getElementById("IdInydRc").value;
        console.log("configuracion " + iduser);
        if (iduser > 1) {
            window.location.href = "@Url.Action("Index","Configuracion",new {Area = "AConfiguracion"})";
        } else {
            console.log("No puede ingresar");
            hablarTexto("Tiene que iniciar sesion para ingresar a Configuracion");
        }


    }

    function funBotones() {
        if (esVisible('vistaBtones')) {
            setOcultar('vistaBtones', true);
        } else {
            setOcultar('vistaBtones', false);
        }
    }

    function funReiniciar() {
        location.reload();
    }

    function funSalir() {
        cerrarSesion();
    }

</script>

<script>
    function funPantalla() {
        if (!document.fullscreenElement) {
            document.documentElement.requestFullscreen().catch(err => {
                console.error(`Error al intentar habilitar pantalla completa: ${err.message}`);
            });
        } else {
            document.exitFullscreen();
        }
    }

</script>



<script id="_favoritos_">
    function funVerFavorito() {
        console.log("ingreso ver favoritos x2");
        let iduser = document.getElementById("IdInydRc").value;
        if (iduser > 1) {
            console.log("entro aqui");
            mostrarFavoritos(iduser);            
        } else {
            console.log("No puede agregar");
            hablarTexto("Tiene que iniciar sesion para ver favoritos");
        }
    }

    async function mostrarFavoritos(idu) {
        console.log("mostrar favoritos x6");

        $("#viewPaginas").html("");
        
        var dataString = new FormData();
        dataString.append("IdUser", idu);
        setOcultar("idLoad1", false);
        document.getElementById("idLoad1").innerHTML = "<i class='fa fa-spinner'> Cargando Recetas ...</i>";

        const response = await fetch('/AReceta/Receta/VerFavoritos', {
            method: 'POST',
            body: dataString
        });
        if (response.ok) {
            const data = await response.text();
            $("#viewPaginas").html(data);
            console.log("exito ver fav");
        }

        setOcultar("idLoad1", true);
    }

</script>